name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Compile and Test
    env:
      MIX_ENV: test
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock')}}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock')}}-${{ hashFiles('lib/**/*.ex')}}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/mix.lock')}}-
            ${{ runner.os }}-build-

      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile dependencies
        run: mix deps.compile

      - name: Compile application
        run: mix compile --warning-as-errors

      - name: Run tests
        run: mix test