name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Compile
    env:
      MIX_ENV: test
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          # FIX 1: Hash both mix.exs and mix.lock
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.exs', '**/mix.lock')}}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get --only $MIX_ENV
          # Note: compile is removed from this step

      # FIX 2: Always run compile. 
      # Mix is fast and will only re-compile files that have changed.
      # This ensures you're testing against your latest source code.
      - name: Compile
        run: mix compile --warning-as-errors

      - name: Run tests
        run: mix test --trace


          

